package com.example.slackr

import android.content.Intent
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Button
import android.widget.EditText
import android.widget.Spinner
import androidx.appcompat.app.AppCompatActivity

class MatchActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_match)

        val mSubject:Spinner = findViewById(R.id.subject)
        val mCode:EditText = findViewById(R.id.code)
        val mFindMatch:Button = findViewById(R.id.findButton)


        val adapter: ArrayAdapter<String> = ArrayAdapter<String>(
            this@MatchActivity,
            android.R.layout.simple_spinner_item, subjectArr
        )

        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        mSubject.adapter = adapter

        mFindMatch!!.setOnClickListener {
            val intent = Intent(this@MatchActivity, CreateGroupPromptActivity::class.java)
            startActivity(intent)
        }
    }

    companion object {
        val subjectArr = arrayOf(
            "AASP",
            "AAST",
            "AGNR",
            "AMSC",
            "AMST",
            "ANSC",
            "ANTH",
            "AOSC",
            "ARAB",
            "ARCH",
            "AREC",
            "ARHU",
            "ARMY",
            "ARSC",
            "ARTH",
            "ARTT",
            "ASTR",
            "BCHM",
            "BEES",
            "BIOE",
            "BIOL",
            "BIOM",
            "BIPH",
            "BISI",
            "BMGT",
            "BMSO",
            "BSCI",
            "BSCV",
            "BSGC",
            "BSOS",
            "BSST",
            "BUAC",
            "BUDT",
            "BUFN",
            "BULM",
            "BUMK",
            "BUSI",
            "BUSM",
            "BUSO",
            "CBMG",
            "CCJS",
            "CHBE",
            "CHEM",
            "CHIN",
            "CHPH",
            "CHSE",
            "CLAS",
            "CLFS",
            "CMLT",
            "CMSC",
            "COMM",
            "CPBE",
            "CPET",
            "CPGH",
            "CPJT",
            "CPMS",
            "CPPL",
            "CPSA",
            "CPSD",
            "CPSF",
            "CPSG",
            "CPSN",
            "CPSP",
            "CPSS",
            "DANC",
            "DATA",
            "EALL",
            "ECON",
            "EDCP",
            "EDHD",
            "EDHI",
            "EDMS",
            "EDSP",
            "EDUC",
            "ENAE",
            "ENCE",
            "ENCH",
            "ENCO",
            "ENEB",
            "ENEE",
            "ENES",
            "ENFP",
            "ENGL",
            "ENMA",
            "ENME",
            "ENPM",
            "ENRE",
            "ENSE",
            "ENSP",
            "ENST",
            "ENTM",
            "ENTS",
            "EPIB",
            "FGSM",
            "FILM",
            "FIRE",
            "FMSC",
            "FREN",
            "GEMS",
            "GEOG",
            "GEOL",
            "GERM",
            "GREK",
            "GVPT",
            "HACS",
            "HDCC",
            "HEBR",
            "HEIP",
            "HESI",
            "HESP",
            "HHUM",
            "HISP",
            "HIST",
            "HLSA",
            "HLSC",
            "HLTH",
            "HNUH",
            "HONR",
            "IDEA",
            "IMDM",
            "IMMR",
            "INAG",
            "INFM",
            "INST",
            "ISRL",
            "ITAL",
            "JAPN",
            "JOUR",
            "JWST",
            "KNES",
            "KORA",
            "LARC",
            "LASC",
            "LATN",
            "LBSC",
            "LGBT",
            "LING",
            "MAIT",
            "MATH",
            "MEES",
            "MIEH",
            "MITH",
            "MLAW",
            "MLSC",
            "MSBB",
            "MSML",
            "MUED",
            "MUSC",
            "NACS",
            "NAVY",
            "NEUR",
            "NFSC",
            "NIAP",
            "NIAV",
            "PEER",
            "PERS",
            "PHIL",
            "PHPE",
            "PHSC",
            "PHYS",
            "PLCY",
            "PLSC",
            "PORT",
            "PSYC",
            "RDEV",
            "RELS",
            "RUSS",
            "SLAA",
            "SLLC",
            "SMLP",
            "SOCY",
            "SPAN",
            "SPHL",
            "STAT",
            "SURV",
            "TDPS",
            "THET",
            "TLPL",
            "TLTC",
            "UMEI",
            "UNIV",
            "URSP",
            "USLT",
            "VMSC",
            "WMST"
        )

    }
}